DROP TABLE employees IF EXISTS;
CREATE TABLE employees (
    id VARCHAR(10) NOT NULL PRIMARY KEY, 
    name VARCHAR(255),
    email VARCHAR(255)
);

DROP TABLE phonebook IF EXISTS;
CREATE TABLE phonebook (
    id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    name varchar(100),
    number varchar(100),
    note varchar(100)
);
